---
version: 2
enable-beta-ecosystems: true

multi-ecosystem-groups:
  infrastructure-dependencies:
    schedule:
      interval: weekly
    commit-message:
      prefix: deps(infra)
    labels:
      - dependencies
      - infra

updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: infrastructure-dependencies
    patterns:
      - '*'

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps(app)
    labels:
      - dependencies
      - apps
    ignore:
      - dependency-name: ruff
        update-types:
          - version-update:semver-minor
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - minor
          - patch
