---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: tests/test_data/
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: \.gitignore

  - repo: local
    hooks:
      - id: python-format
        name: Format Python files
        description: Format Python files
        language: system
        entry: make format
        types_or:
          - python
          - pyi

      - id: python-lint
        name: Lint Python files
        description: Lint Python files
        language: system
        entry: make lint
        args:
          - LINT_OPTIONS=--fix --exit-non-zero-on-fix
        types_or:
          - python
          - pyi

  - repo: https://github.com/hadolint/hadolint
    rev: 57e1618d78fd469a92c1e584e8c9313024656623  # frozen: v2.14.0
    hooks:
      - id: hadolint
        args:
          - --failure-threshold
          - error

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 5030dca3047414c338091455ac41803200ec1f0f  # frozen: 0.37.3
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: ade0f95ddcf661c697d4670d2cfcbe95d0048a0a  # frozen: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
        args:
          - --no-schema
      - id: taplo-lint
        name: Validate pyproject schema
        args:
          - --schema
          - https://json.schemastore.org/pyproject.json
        files: ^pyproject\.toml$

  - repo: https://github.com/lyz-code/yamlfix
    rev: f857ca370af3db7e5e181373d45c06a148fac3f8  # frozen: 1.19.1
    hooks:
      - id: yamlfix
        args:
          - --config-file
          - .yamlfix.toml

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/sirwart/ripsecrets
    rev: 7d94620933e79b8acaa0cd9e60e9864b07673d86  # frozen: v0.1.11
    hooks:
      - id: ripsecrets
