"""Add fail_reason string column

Revision ID: 095a3873bec8
Revises: 2745a5bf4c97
Create Date: 2023-06-26 15:36:56.507857

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "095a3873bec8"
down_revision = "2745a5bf4c97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("fail_reason", sa.String(), nullable=True))
    op.execute("ALTER TYPE status ADD VALUE 'FAILED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "fail_reason")
    # ### end Alembic commands ###
