"""initial

Revision ID: 0ad8044bf4d5
Revises:
Create Date: 2023-05-09 17:10:34.139530

"""
import sqlalchemy as sa
from sqlalchemy import FetchedValue

from alembic import op

# revision identifiers, used by Alembic.
revision = "0ad8044bf4d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packages",
        sa.Column("package_id", sa.UUID(), server_default=FetchedValue(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("QUEUED", "PENDING", "FINISHED", name="status"), nullable=False),
        sa.PrimaryKeyConstraint("package_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packages")
    # ### end Alembic commands ###
