"""One to many package to rules

Revision ID: 0c4e434fc0b6
Revises: b053c5bacf42
Create Date: 2023-05-20 17:41:39.307836

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c4e434fc0b6"
down_revision = "b053c5bacf42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("package_rules")
    op.add_column("rules", sa.Column("package_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "rules", "packages", ["package_id"], ["package_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rules", type_="foreignkey")
    op.drop_column("rules", "package_id")
    op.create_table(
        "package_rules",
        sa.Column("package_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("rule_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["package_id"], ["packages.package_id"], name="package_rules_package_id_fkey"),
        sa.ForeignKeyConstraint(["rule_name"], ["rules.name"], name="package_rules_rule_name_fkey"),
    )
    # ### end Alembic commands ###
