"""Adpated the scan table to no longer store information related to queuing scans,
and rather, only the results of a scan

Revision ID: 0dade8a4a303
Revises: 9d70bac89aa5
Create Date: 2023-08-04 12:33:37.738832

"""
import sqlalchemy as sa
from sqlalchemy.schema import FetchedValue

from alembic import op

# revision identifiers, used by Alembic.
revision = "0dade8a4a303"
down_revision = "9d70bac89aa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), server_default=FetchedValue(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scans",
        sa.Column("scan_id", sa.UUID(), server_default=FetchedValue(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("inspector_url", sa.String(), nullable=True),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reported_by", sa.String(), nullable=True),
        sa.Column("commit_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("scan_id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "download_urls",
        sa.Column("id", sa.UUID(), server_default=FetchedValue(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.scan_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "package_rules",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.scan_id"],
        ),
        sa.PrimaryKeyConstraint("scan_id", "rule_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("package_rules")
    op.drop_table("download_urls")
    op.drop_table("scans")
    op.drop_table("rules")
    # ### end Alembic commands ###
