"""Store commit hash in scan

Revision ID: 2745a5bf4c97
Revises: 883af2539440
Create Date: 2023-06-20 16:56:21.809460

"""
import uuid

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2745a5bf4c97"
down_revision = "883af2539440"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop the package_rules.rule_name column
    op.drop_column("package_rules", "rule_name")

    # Add a column "rule_id" to "package_rules"
    op.add_column("package_rules", sa.Column("rule_id", sa.UUID(), server_default=sa.FetchedValue(), nullable=False))

    # Drop the primary key constraint on rules.name
    op.drop_constraint("rules_pkey", "rules", type_="primary")

    # Add a UNIQUE constraint to rules.name
    op.create_unique_constraint("rules_pkey", "rules", ["name"])

    # Add the "id" column to the rules table, make it the new primary key
    op.add_column(
        "rules",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            server_default=sa.FetchedValue(),
            default=uuid.uuid4,
            nullable=True,  # Changed later
            primary_key=True,
            unique=True,
        ),
    )

    op.execute("UPDATE rules SET id = gen_random_uuid();")
    op.alter_column("rules", "id", nullable=False)

    # Then add a foreign key constraint that links package_rules.rule_id to rules.id
    op.create_foreign_key("package_rules_rule_id_fkey", "package_rules", "rules", ["rule_id"], ["id"])

    # Add the "commit_hash" column to the packages table
    op.add_column("scans", sa.Column("commit_hash", sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("package_rules", "rule_id")
    op.add_column("package_rules", sa.Column("rule_name", sa.String(), nullable=False))

    op.drop_column("rules", "id")
    op.create_primary_key("rules_pkey", "rules", ["name"])

    op.create_foreign_key("package_rules_rule_name_fkey", "package_rules", "rules", ["rule_name"], ["name"])

    op.drop_column("packages", "commit_hash")
    # ### end Alembic commands ###
