"""Store commit hash in scan

Revision ID: 2745a5bf4c97
Revises: 5e46ee8ec64f
Create Date: 2023-06-20 16:56:21.809460

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2745a5bf4c97"
down_revision = "5e46ee8ec64f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("package_rules", "rule_name")
    op.add_column("package_rules", sa.Column("rule_id", sa.UUID(), nullable=False))
    op.add_column(
        "rules", sa.Column("id", sa.UUID(), server_default=sa.FetchedValue(), nullable=False, primary_key=True)
    )

    op.create_foreign_key(None, "package_rules", "rules", ["rule_id"], ["id"])
    op.add_column("packages", sa.Column("commit_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "id")
    op.drop_column("packages", "commit_hash")
    op.add_column("package_rules", sa.Column("rule_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "package_rules", type_="foreignkey")
    op.create_foreign_key("package_rules_rule_name_fkey", "package_rules", "rules", ["rule_name"], ["name"])
    op.drop_column("package_rules", "rule_id")
    # ### end Alembic commands ###
