"""add score and most_malicious_file

Revision ID: 5264b2894e56
Revises: 0ad8044bf4d5
Create Date: 2023-05-09 20:26:28.054311

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5264b2894e56"
down_revision = "0ad8044bf4d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("score", sa.Integer(), nullable=True))
    op.add_column("packages", sa.Column("most_malicious_file", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packages", "most_malicious_file")
    op.drop_column("packages", "score")
    # ### end Alembic commands ###
