"""Add queued_by, pending_by, and finished_by fields

Revision ID: 5e46ee8ec64f
Revises: 00171406f182
Create Date: 2023-06-13 17:06:09.364563

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e46ee8ec64f"
down_revision = "00171406f182"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("queued_by", sa.String(), nullable=False))
    op.add_column("packages", sa.Column("pending_by", sa.String(), nullable=True))
    op.add_column("packages", sa.Column("finished_by", sa.String(), nullable=True))
    op.drop_column("packages", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("packages", "finished_by")
    op.drop_column("packages", "pending_by")
    op.drop_column("packages", "queued_by")
    # ### end Alembic commands ###
