"""add download_urls.scan_id index

Revision ID: 6c8e52cd4f5f
Revises: 9d70bac89aa5
Create Date: 2023-09-22 23:20:24.558396

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c8e52cd4f5f"
down_revision = "9d70bac89aa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_download_urls_scan_id"), "download_urls", ["scan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_download_urls_scan_id"), table_name="download_urls")
    # ### end Alembic commands ###
