"""many to many

Revision ID: 6e1ee71402d0
Revises: 0c4e434fc0b6
Create Date: 2023-05-20 19:35:39.797309

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6e1ee71402d0"
down_revision = "0c4e434fc0b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_rules",
        sa.Column("package_id", sa.UUID(), nullable=True),
        sa.Column("rule_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_name"],
            ["rules.name"],
        ),
    )
    op.drop_constraint("rules_package_id_fkey", "rules", type_="foreignkey")
    op.drop_column("rules", "package_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rules", sa.Column("package_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key("rules_package_id_fkey", "rules", "packages", ["package_id"], ["package_id"])
    op.drop_table("package_rules")
    # ### end Alembic commands ###
