"""reported at timestamp

Revision ID: 98de0cdba2c2
Revises: b5ec215f4679
Create Date: 2023-05-10 18:28:10.211469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98de0cdba2c2'
down_revision = 'b5ec215f4679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('reported_at', sa.DateTime(), nullable=False))
    op.drop_column('packages', 'reported')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('reported', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('packages', 'reported_at')
    # ### end Alembic commands ###
