"""add scans status index

Revision ID: 9ac5b6c4a36b
Revises: b6c8e52cd4f5f
Create Date: 2023-09-23 00:07:33.273030

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9ac5b6c4a36b"
down_revision = "6c8e52cd4f5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_scans_status"),
        "scans",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'QUEUED' OR status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scans_status"), table_name="scans", postgresql_where=sa.text("status = 'QUEUED' OR status = 'PENDING'")
    )
    # ### end Alembic commands ###
