"""Add APIClient table

Revision ID: af5a0e26c976
Revises: 9d70bac89aa5
Create Date: 2023-07-28 18:47:42.055185

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "af5a0e26c976"
down_revision = "9d70bac89aa5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_clients",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("hashed_secret", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=True, default=False),
        sa.PrimaryKeyConstraint("client_id"),
        sa.UniqueConstraint("client_id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_clients")
    # ### end Alembic commands ###
