"""Add inspector_url column

Revision ID: b053c5bacf42
Revises: d4c81f4086ce
Create Date: 2023-05-14 21:45:46.545896

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b053c5bacf42"
down_revision = "d4c81f4086ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("inspector_url", sa.String(), nullable=True))
    op.drop_column("packages", "most_malicious_file")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("packages", sa.Column("most_malicious_file", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("packages", "inspector_url")
    # ### end Alembic commands ###
