"""Make queued_at optional

Revision ID: c3f59638859f
Revises: 1bced040ba5a
Create Date: 2023-05-12 18:02:55.740346

"""
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c3f59638859f"
down_revision = "1bced040ba5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("packages", "queued_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("packages", "queued_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
