"""Added finished_at column to scans

Revision ID: ea1e83d44157
Revises: 0dade8a4a303
Create Date: 2023-08-04 12:45:55.027674

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ea1e83d44157"
down_revision = "0dade8a4a303"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "finished_at")
    # ### end Alembic commands ###
