---
name: Migration as SQL

on:
  pull_request:
    paths:
      - alembic/versions/**

concurrency:
  group: migration-sql-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  comment:
    name: Generate migration SQL

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout (base)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Setup uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-default-groups

      - name: Get the base migration revision
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          base_head="$(uv run alembic heads | awk '{print $1}')"
          if [ -z "${base_head}" ] || [ "$(wc -l <<<"${base_head}")" -ne 1 ]; then
            echo >&2 'Exactly one migration head is required'
            exit 1
          fi

          echo "Base migration revision: ${base_head}"
          echo "BASE_MIGRATION_REVISION=${base_head}" >>"${GITHUB_ENV}"

      - name: Checkout (HEAD)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          clean: false
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate SQL
        id: sql
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          base="${BASE_MIGRATION_REVISION}"

          # `alembic upgrade --sql` outputs the SQL to stdout, and the logs to stderr
          uv run alembic upgrade --sql "${base}:head" >up.sql 2>up.log

          # `alembic downgrade --sql` outputs the SQL to stdout, and the logs to stderr
          uv run alembic downgrade --sql "head:${base}" >down.sql 2>down.log

      - name: Upload migration SQL
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          if-no-files-found: error
          name: migration-sql
          path: |
            up.sql
            up.log
            down.sql
            down.log
          retention-days: 14
